In [1]:
# Import the necessary libraries
# data transformation
import pandas as pd
import numpy as np
from functools import reduce

# plotting
import matplotlib.pyplot as plt
#from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
import seaborn as sns
from matplotlib import gridspec
from pylab import *
import matplotlib.patches as mpatches

# map plotting
#import geopandas as gpd
#from shapely.geometry import Point
#from mpl_toolkits.axes_grid1 import make_axes_locatable



In [2]:
#!pip install jupyter_contrib_nbextensions
#!jupyter contrib nbextension install --sys-prefix

In [3]:
#!jupyter nbextension enable Toc2/main --sys-prefix


Enabling notebook extension Toc2/main...
      - Validating: ok


# Data Import

In [2]:
import datetime
# # VALUE: pandas dtype
datatypes = {
#    "Date Created": "pd.datetime",
    "Borough": "int",
    "Map Atlas": "category",
    "Block": "category",
    "Lot": "category",
    "Address": "str",
    "Parcel Name": "str",
    "Agency": "category",
    "Current Uses": "str",
    "Total Area": "int",
    "Open Petroleum Spill": "category",
    "Govt Clean-Up Program": "category",
    "Structure Completed": "category",
    "Number Structures": "int",
    "Total Gross Area Structures": "int",
    "Ratio Building to Floor Area": "float",
    "Allowable Building to Floor Area": "float",
    "Land Use Category": "category",
    "Community Board": "category",
    "Census Tract": "category",
    "Census Block": "category",
    "School Dist": "category",
    "Council District": "category",
    "Postcode": "category",
    "Fire Comp": "category",
    "Health Area": "category",
    "Health Ctr": "category",
    "Police Prct": "category",
    "Major Use": "category",
    "Number of Easements": "int",
    "Commercial Floor Area": "int",
    "Residential Floor Area": "int",
    "Office Floor Area": "int",
    "Retail Floor Area": "int",
    "Garage Floor Area": "int",
    "Storage Floor Area": "int",
    "Factory Floor Area": "int",
    "Other Floor Area": "int",
    "Num Floors": "float",
    "Residential Units": "int",
    "Residential and Non-Residential Units": "int",
    "Lot Front": "float",
    "Lot Depth": "float",
    "Bldg Front": "float",
    "Bldg Depth": "float",
    "Proximity Code": "category",
    "Irr Lot Code": "str",
    "Lot Type Code": "category",
    "Bsmt Code": "category",
    "Assess Land": "float",
    "Exempt Land": "float",
    "Exempt Tot": "float",
    "Year Alter 1": "category",
    "Year Alter 2": "category",
    "His Dist": "category",
    "Landmark": "str",
    "Condominium Number": "category",
    "Coordinates": "str",
    "E-Designation Number": "category",
    "Industrial Business Zone": "category",
    "Zone Dist": "category",
    "Zone Dist 2": "category",
    "Overlay 1": "category",
    "Overlay 2": "category",
    "SP Dist 1": "category",
    "SP Dist 2": "category",
    "Potential Urban Ag": "category",
    "Contact": "str",
    "EDC % Occupied": "float",
    "Pluto Version": "category",
    "Latitude": "float",
    "Longitude": "float",
    "BIN": "str",
    "NTA": "category"
}
# Similarly, each column will have to have a different method of handling missing values.
# KEY: proper name
# VALUE: missing value type
nan = np.nan
nas = {
#    "Date Created": nan,
    "Borough": "",
    "Map Atlas": "",
    "Block": nan,
    "Lot": nan,
    "Address": "",
    "Parcel Name": "",
    "Agency": "",
    "Current Uses": "",
    "Total Area": nan,
    "Open Petroleum Spill": "",
    "Govt Clean-Up Program": "",
    "Structure Completed": nan,
    "Number Structures": nan,
    "Total Gross Area Structures": nan,
    "Ratio Building to Floor Area": nan,
    "Allowable Building to Floor Area": nan,
    "Land Use Category": "",
    "Community Board": "",
    "Census Tract": nan,
    "Census Block": "",
    "School Dist": "",
    "Council District": "",
    "Postcode": "",
    "Fire Comp": "",
    "Health Area": "",
    "Health Ctr": "",
    "Police Prct": "",
    "Major Use": "",
    "Number of Easements": nan,
    "Commercial Floor Area": nan,
    "Residential Floor Area": nan,
    "Office Floor Area": nan,
    "Retail Floor Area": nan,
    "Garage Floor Area": nan,
    "Storage Floor Area": nan,
    "Factory Floor Area": nan,
    "Other Floor Area": nan,
    "Num Floors": nan,
    "Residential Units": nan,
    "Residential and Non-Residential Units": nan,
    "Lot Front": nan,
    "Lot Depth": nan,
    "Bldg Front": nan,
    "Bldg Depth": nan,
    "Proximity Code": "",
    "Irr Lot Code": "",
    "Lot Type Code": "",
    "Bsmt Code": "",
    "Assess Land": nan,
    "Exempt Land": nan,
    "Exempt Tot": nan,
    "Year Alter 1": nan,
    "Year Alter 2": nan,
    "His Dist": "",
    "Landmark": "",
    "Condominium Number": nan,
    "Coordinates": "",
    "E-Designation Number": "",
    "Industrial Business Zone": "",
    "Zone Dist": "",
    "Zone Dist 2": "",
    "Overlay 1": "",
    "Overlay 2": "",
    "SP Dist 1": "",
    "SP Dist 2": "",
    "Potential Urban Ag": "",
    "Contact": "",
    "EDC % Occupied": nan,
    "Pluto Version": "",
    "Latitude": nan,
    "Longitude": nan,
    "BIN": "",
    "NTA": ""
}
# Read in the data.
nyc = pd.read_csv(
    "C:\DataSets\city-owned-and-leased-property-local-law-48-of-2011.csv",
    dtype=datatypes,
    na_values=nas)

nyc.head()


Date Created  Borough Map Atlas Block Lot             Address  \
0  2013-12-11T00:00:00        1         4     2   1     MARGINAL STREET   
1  2013-12-11T00:00:00        1         4     2  23              PIER 6   
2  2013-12-11T00:00:00        1         4     3   1        BATTERY PARK   
3  2013-12-11T00:00:00        1         4     3   2  PETER MINUIT PLAZA   
4  2013-12-11T00:00:00        1         4     3   3  PETER MINUIT PLAZA   

                     Parcel Name     Agency  \
0  BATTERY MARITIME BLDG / FERRY  DOT, DSBS   
1                         PIER 6       DSBS   
2                   BATTERY PARK      PARKS   
3  PETER MINUIT PLAZA/BATTERY PK      PARKS   
4  PETER MINUIT PLAZA/BATTERY PK      PARKS   

                                        Current Uses  Total Area  ...  \
0        FERRY TERMINAL, WATERFRONT PROPERTY, NO USE      209215  ...   
1  NO USE, FINAL COMMITMNT-DISP, IN USE-TENANTED,...      510025  ...   
2                                               PARK      945425  ...   
3                                               PARK       39900  ...   
4                                               PARK       33600  ...   

  SP Dist 1 SP Dist 2 Potential Urban Ag  \
0        LM       NaN                NaN   
1        LM       NaN                NaN   
2       NaN       NaN                NaN   
3       NaN       NaN                NaN   
4       NaN       NaN                NaN   

                                             Contact  EDC % Occupied  \
0  Christian Grove cgrove@dcas.nyc.gov  212 386-0613             0.0   
1  Christian Grove cgrove@dcas.nyc.gov  212 386-0613             0.0   
2  Christian Grove cgrove@dcas.nyc.gov  212 386-0613             0.0   
3  Christian Grove cgrove@dcas.nyc.gov  212 386-0613             0.0   
4  Christian Grove cgrove@dcas.nyc.gov  212 386-0613             0.0   

   Pluto Version   Latitude  Longitude      BIN  \
0           13v1        NaN        NaN      NaN   
1           13v1  40.701481 -74.009171  1075697   
2           13v1  40.702880 -74.015523  1000000   
3           13v1  40.702153 -74.013146  1085598   
4           13v1  40.702153 -74.013146  1085598   

                                 NTA  
0                                NaN  
1  Battery Park City-Lower Manhattan  
2        park-cemetery-etc-Manhattan  
3  Battery Park City-Lower Manhattan  
4  Battery Park City-Lower Manhattan  

[5 rows x 74 columns]

## Land Assessment Data for Year 2017

In [3]:
import time
import datetime
  
now = time.localtime(time.time())
print (time.asctime(now))


nyc.d = pd.to_datetime(nyc['Date Created'])
#nyc.dtypes
#nyc['Date Created'] 

#d.dt.year

#time stamp
ts = pd.to_datetime('1/1/2017')
print (ts)

#slicing the data to only 2017 records
    #  nyc.loc[nyc.d >= ts]

nyc2 = nyc.loc[nyc.d >= ts]

nyc2.info()


Fri Jun 14 18:45:48 2019
2017-01-01 00:00:00
<class 'pandas.core.frame.DataFrame'>
Int64Index: 13580 entries, 42370 to 55949
Data columns (total 74 columns):
Date Created                             13580 non-null object
Borough                                  13580 non-null int32
Map Atlas                                0 non-null category
Block                                    13580 non-null category
Lot                                      13580 non-null category
Address                                  13559 non-null object
Parcel Name                              10269 non-null object
Agency                                   13515 non-null category
Current Uses                             13504 non-null object
Total Area                               13580 non-null int32
Open Petroleum Spill                     608 non-null category
Govt Clean-Up Program                    50 non-null category
Structure Completed                      13580 non-null category
Number Structures   

C:\Users\solan\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  


## Subset Data

In [4]:
# create numeric fields to look at
numeric_fields = list(nyc2.select_dtypes(include=['int', 'float']).columns)

numeric_fields = numeric_fields[0:25]

#print(numeric_fields)
print('----')

#remove the comment sign to calculate and run some simple statistics
#print('Numeric Fields - Means:', nyc_numeric[1:25].mean())
#print('Numeric Fields - Median:', nyc_numeric[1:25].median())

numeric_fields.append("Proximity Code")
numeric_fields.append("Land Use Category")

#print(numeric_fields)
print (numeric_fields[0:27])

nyc_numeric = nyc2[numeric_fields]

nyc_numeric.shape

----
['Borough', 'Total Area', 'Number Structures', 'Total Gross Area Structures', 'Ratio Building to Floor Area', 'Allowable Building to Floor Area', 'Number of Easements', 'Commercial Floor Area', 'Residential Floor Area', 'Office Floor Area', 'Retail Floor Area', 'Garage Floor Area', 'Storage Floor Area', 'Factory Floor Area', 'Other Floor Area', 'Num Floors', 'Residential Units', 'Residential and Non-Residential Units', 'Lot Front', 'Lot Depth', 'Bldg Front', 'Bldg Depth', 'Assess Land', 'Exempt Land', 'Exempt Tot', 'Proximity Code', 'Land Use Category']


(13580, 27)

# Training and Testing Split

## Using Numeric Fields to Predict Land Use Category  

In [5]:
##  We will use Agency and Current Uses features to predict the Land Use number.  
#'Borough','Agency','Land Use Category'

#print(df.isnull().sum())
#print(df.notnull().sum())

##replacing NaN values referencing Austin Simeone's code that we worked on together as a team on Sunday 6/9/19
for column in nyc_numeric[:1]:
    nyc_numeric[column] = nyc_numeric[column].interpolate(method = 'ffill')


df = nyc_numeric

df.info()

df.shape


print(df.isnull().sum())
print(df.notnull().sum())
    



C:\Users\solan\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


<class 'pandas.core.frame.DataFrame'>
Int64Index: 13580 entries, 42370 to 55949
Data columns (total 27 columns):
Borough                                  13580 non-null int32
Total Area                               13580 non-null int32
Number Structures                        13580 non-null int32
Total Gross Area Structures              13580 non-null int32
Ratio Building to Floor Area             13580 non-null float64
Allowable Building to Floor Area         13580 non-null float64
Number of Easements                      13580 non-null int32
Commercial Floor Area                    13580 non-null int32
Residential Floor Area                   13580 non-null int32
Office Floor Area                        13580 non-null int32
Retail Floor Area                        13580 non-null int32
Garage Floor Area                        13580 non-null int32
Storage Floor Area                       13580 non-null int32
Factory Floor Area                       13580 non-null int32
Other Floor Are

In [ ]:
#DO NOT RUN ---  HOT ENCODING

# perform one-hot encoding of the categorical data "Land Use Category" since this is what we will predicting

#tmp_df2 = pd.get_dummies(df['Land Use Category'],prefix='LaUseCat')

#df = pd.concat((df,tmp_df2), axis=1) # add back into the dataframe


#df
#tmp_df2 = pd.get_dummies(df['Land Use Category'],prefix='LaUseCat')
#df = pd.concat((df,tmp_df2), axis=1) # add back into the dataframe



#df_grouped = df.groupby(by=['Land Use Category'])

#print(df_grouped['Land Use Category'].count())
#print(df.LaUseCat_11)
#df.head()
#df.info

In [12]:
from sklearn.model_selection import ShuffleSplit

# NOTE: Referencing and modified Dr. Larson's code to get my training and testing split using sklearn and 
# we want to predict the X and y data as follows:

if 'Land Use Category' in df:
    y = df['Land Use Category'].values
    del df['Land Use Category']
    X = df.values # use 'Agency' and 'Current Uses'  to predict!

    ## X and y are now numpy matrices, by calling 'values' on the pandas data frames we
    #    have converted them into simple matrices to use with scikit learn
    
    
# to use the cross validation object in scikit learn, we need to grab an instance
#    of the object and set it up. This object will be able to split our data into 
#    training and testing splits


num_cv_iterations = 16

num_instances = len(y)


# test and train split

cv_object = ShuffleSplit(n_splits=num_cv_iterations, test_size  = 0.2)

print(num_instances)
print(cv_object)


df.head()
print(shape(X),shape(y))
y


13580
ShuffleSplit(n_splits=16, random_state=None, test_size=0.2, train_size=None)
(13580, 26) (13580,)


[7, 7, 7, 7, 9, ..., 7, 7, 8, 11, 8]
Length: 13580
Categories (11, object): [1, 10, 11, 2, ..., 6, 7, 8, 9]

# Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics as mt

## NOTE:  Leveranging Dr. Larson's code from here down:


lr_clf = LogisticRegression(penalty='l2', C=1.0, class_weight=None) # get object
lr_clf

# now we can use the cv_object that we setup before to iterate through the 
#    different training and testing sets. Each time we will reuse the logisitic regression 
#    object, but it gets trained on different data each time we use it.

iter_num=0
# the indices are the rows used for training and testing in each iteration

for train_indices, test_indices in cv_object.split(X,y): 
    
    # I will create new variables here so that it is more obvious what 
    # the code is doing (you can compact this syntax and avoid duplicating memory,
    # but it makes this code less readable)
    X_train = X[train_indices]
    y_train = y[train_indices]
    
    X_test = X[test_indices]
    y_test = y[test_indices]
    
    #print (X_train)   
    


In [14]:
from sklearn import metrics as mt

# train the reusable logisitc regression model on the training data
    
lr_clf.fit(X_train,y_train)  # train object
    
y_hat = lr_clf.predict(X_test) # get test set preditions

# now let's get the accuracy and confusion matrix for this iterations of training/testing
acc = mt.accuracy_score(y_test,y_hat)
conf = mt.confusion_matrix(y_test,y_hat)
print("====Iteration",iter_num," ====")
print("accuracy", acc )
print("confusion matrix\n",conf)
iter_num+=1
    

C:\Users\solan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\solan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


====Iteration 0  ====
accuracy 0.5412371134020618
confusion matrix
 [[  0   0   0   0   1   0   0   0   1   8   3]
 [  0   6   1   0   0   0   1   0  15   0  83]
 [  0   3 231   0   0   2   0   1   0   1 770]
 [  0   0   0   0  28   4   0   0   0   3   0]
 [  0   0   0   0   3   1   0   0   0   3   0]
 [  0   0   0   0  10   2   3   0   0  10   1]
 [  0   0   0   0   0   0  44   0   2  28   0]
 [  0   1   0   0   0   0   0  17   3   0   0]
 [  4   3  13   0   0  49   0   0  21  14  77]
 [  0   0   1   0   0   0   6   3  26 379   8]
 [  0   1  36   0   0   4   0   0   8   6 767]]


C:\Users\solan\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
